function ENT:ClearScreen()
    net.Start("TempleOS_Clear")
    net.WriteEntity(self)
    net.Broadcast()
end
function ENT:DoClientCommand(msg)
    net.Start("TempleOS_Command")
    net.WriteEntity(self)
    net.WriteString(msg)
    net.Broadcast()
end
function ENT:Print(msg,col)
    net.Start("TempleOS_Print")
    net.WriteEntity(self)
    net.WriteString(msg)
    net.WriteColor(col or holylua.color[1])
    net.Broadcast()
end
function ENT:PrintInternal(msg,col)
    net.Start("TempleOS_Print")
    net.WriteEntity(self)
    net.WriteString(msg)
    net.WriteColor(col or holylua.color[1])
    net.WriteBool(false)
    net.Broadcast()
end
 
net.Receive("TempleOS_Input", function()
    local ent = net.ReadEntity()
    local msg = net.ReadString()
    net.Start("TempleOS_Print")
    net.WriteEntity(ent)
    net.WriteString(msg)
    net.WriteColor(holylua.color[2])
    net.Broadcast()
    ent:ApplyCommand(msg)
end)